name: Deploy as Minio

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Assembly
        run: sbt assembly

      - name: Move file
        run: rm -rf dist/ && mkdir dist && cp target/scala-2.12/obo-parser.jar dist/

      - name: Minio Deploy jar
        uses: hkdobrev/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_CLIN_QA_AWS_ENDPOINT }}
          access_key: ${{ secrets.MINIO_CLIN_QA_AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.MINIO_CLIN_QA_AWS_SECRET_ACCESS_KEY }}
          bucket: 'clin-qa-app-datalake'
          source_dir: 'dist'
          target_dir: '/spark'
